remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Inform치tica ESO y Bachiller
description: P치gina de apoyo con materiales para las asignaturas de inform치tica de ESO y Bachiller.
show_menu: true
github:
  is_project_page: false
volver_pagina_principal: true
autor:
  mostrar: true
  nombre: David L칩pez Castellote